- add rc orin for dcs 2.0
airvolute/dcs-deploy pull request #10
Opened 2023-09-14 06:27 UTC by MartinSedlacek

Added RC for orin_nx dcs 2.0.
- updated script and added new configuration

2023-09-20 10:35 UTC, MartinSedlacek commented
This is postponed for a while. This works with at least one time flashed Orin NX, but it is not working with brand new one due to not flashing internals.

2023-10-25 13:57 UTC, eMrazSVK requested changes
Basically just formatting changes. Other than that, I'm good with merging this one.

2023-10-25 13:57 UTC, eMrazSVK commented on dcs_deploy.py
> +            pass
This might be forgotten `pass` here.
```suggestion
```

2023-10-25 13:57 UTC, eMrazSVK commented on dcs_deploy.py
> +                pass
Unnecessary pass
```suggestion
```

2023-10-25 13:57 UTC, eMrazSVK commented on dcs_deploy.py
> +
```suggestion

```

2023-10-25 13:57 UTC, eMrazSVK commented on dcs_deploy.py
> +
```suggestion

```

2023-10-25 13:57 UTC, eMrazSVK commented on dcs_deploy.py
> +        """
```suggestion
        """
```

2023-10-25 13:57 UTC, eMrazSVK commented on dcs_deploy.py
> +        return ret
```suggestion
        return ret
```

2024-01-08 09:31 UTC, closed without merging